/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingRequest {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'serviceType' : string,
  'submittedAt' : bigint,
  'email' : string,
  'preferredDate' : string,
  'phone' : string,
}
export interface ContactForm {
  'id' : bigint,
  'serviceType' : string,
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface Service {
  'name' : string,
  'description' : string,
  'iconName' : string,
  'category' : string,
}
export interface Testimonial {
  'id' : bigint,
  'customerName' : string,
  'review' : string,
  'date' : string,
  'rating' : bigint,
  'location' : string,
}
export interface _SERVICE {
  'getAllBookings' : ActorMethod<[], Array<BookingRequest>>,
  'getAllContacts' : ActorMethod<[], Array<ContactForm>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'submitBooking' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'submitContact' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'submitTestimonial' : ActorMethod<
    [string, string, bigint, string],
    undefined
  >,
  'updateBookingStatus' : ActorMethod<[bigint, string], BookingRequest>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];